### ISSUE TITLE
"Part 2 - Add Monkey Dialog" - trying to build and run it as it -> "The project needs to be deployed before we can debug. Please enable Deploy in the Configuration Manager.""

### ISSUE THREAD

**Issue by ShamilS** [dotnet-presentations/blazor-hybrid-workshop#2]
- opened `MonkeyFinderHybrid.sln` in VS 2022
- NuGet packages were restored automatically;
- rebuilt was OK:

    Rebuild started at 0:04...
    1>------ Rebuild All started: Project: MonkeyFinderHybrid, Configuration: Debug Any CPU ------
    Restored S:\Learning\Blazor\blazor-hybrid-workshop-main\Part 2 - Add Monkey Dialog\MonkeyFinderHybrid\MonkeyFinderHybrid.csproj (in 825 ms).
    1>MonkeyFinderHybrid -> S:\Learning\Blazor\blazor-hybrid-workshop-main\Part 2 - Add Monkey Dialog\MonkeyFinderHybrid\bin\Debug\net8.0-ios\iossimulator-x64\MonkeyFinderHybrid.dll
    1>MonkeyFinderHybrid -> S:\Learning\Blazor\blazor-hybrid-workshop-main\Part 2 - Add Monkey Dialog\MonkeyFinderHybrid\bin\Debug\net8.0-maccatalyst\maccatalyst-x64\MonkeyFinderHybrid.dll
    1>MonkeyFinderHybrid -> S:\Learning\Blazor\blazor-hybrid-workshop-main\Part 2 - Add Monkey Dialog\MonkeyFinderHybrid\bin\Debug\net8.0-android\MonkeyFinderHybrid.dll
    1>MonkeyFinderHybrid -> S:\Learning\Blazor\blazor-hybrid-workshop-main\Part 2 - Add Monkey Dialog\MonkeyFinderHybrid\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\MonkeyFinderHybrid.dll
    ========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
    ========== Rebuild completed at 0:05 and took 43.527 seconds ==========
    
- Debug -> `Start without debugging`:

![TheProjectNeedsToDeployed](https://github.com/user-attachments/assets/493cd7c7-c863-4d64-b581-59db5df197be)

- Right-click on project name, select `Deploy` -> output:

    Creating a new clean layout...
    Copying files: Total 43 mb to layout...
    DEP1000: Cannot copy file "C:\Users\admin\.nuget\packages\microsoft.fluentui.aspnetcore.components\4.9.3\staticwebassets\Components\DesignSystemProvider\FluentDesignTheme.razor.js" to layout "S:\Learning\Blazor\blazor-hybrid-workshop-main\Part 2 - Add Monkey Dialog\MonkeyFinderHybrid\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\wwwroot\_content\Microsoft.FluentUI.AspNetCore.Components\Components\DesignSystemProvider\FluentDesignTheme.razor.js". DirectoryNotFoundException - Could not find a part of the path 'S:\Learning\Blazor\blazor-hybrid-workshop-main\Part 2 - Add Monkey Dialog\MonkeyFinderHybrid\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\wwwroot\_content\Microsoft.FluentUI.AspNetCore.Components\Components\DesignSystemProvider\FluentDesignTheme.razor.js'. [0x80070003]
    ========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
    ========== Build completed at 0:17 and took 00.641 seconds ==========
    ========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========
    ========== Deploy completed at 0:17 and took 00.641 seconds ==========

- Tried again: Debug -> `Start without debugging`:

![TheProjectNeedsToDeployed](https://github.com/user-attachments/assets/493cd7c7-c863-4d64-b581-59db5df197be)

---

* I see the similar to the subject issue discussion here [Question: The project needs to be deployed before we can debug](https://github.com/microsoft/microsoft-ui-xaml/issues/6378) but no (?) effective solution.

Do you have an effective solution of the subject issue? Did you try to go through your tutorial "Part 2 - Add Monkey Dialog" source code on a fresh PC?

**Comment by ShamilS** [comment]
continued...

Target deployment folder `S:\Learning\Blazor\blazor-hybrid-workshop-main\Part 2 - Add Monkey Dialog\MonkeyFinderHybrid\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\wwwroot\_content\Microsoft.FluentUI.AspNetCore.Components\Components\DesignSystemProvider`

exists. But is has blanks. Could these blanks be the source/cause of the subject issue? Let's check:

When the whole solution folder with all the files was moved to the `S:\Learning\Blazor\Issue` folder, NuGet packages restored, solution cleared, closed, rebuilt then the `The project needs to be deployed...` issue disappeared. So I can assume the subject issue was caused by the target deployment fullpath having blanks.

But when I have tried to run the project's first time the result program window was:

![AnUnahndledErrorHasOccurred](https://github.com/user-attachments/assets/48890f19-fdf4-4638-b45a-656e5a66c1fa)

After a few more tries I have got the positive result program window:

![FinallyAllMonkyesAreHere](https://github.com/user-attachments/assets/3acad04e-d74d-4585-91c2-4a9c3014060c)

Still unclear why on first runs the result was an "Unhandled exception"  (debug/trace mode didn't allow to catch the source of this error).

So the recommendations would be:

- to change the naming of the tutorial chapters for them to not have blank (or hyphen/dash - '-' ?) chars;
- to introduce unhandled errors handling code in the very first sample project.

**Comment by jfversluis** [comment]
Just tried this and its caused by the infamous maximum file path length in Windows. Looking at your error message, the target path (S:\Learning\Blazor\blazor-hybrid-workshop-main\Part 2 - Add Monkey Dialog\MonkeyFinderHybrid\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\wwwroot\_content\Microsoft.FluentUI.AspNetCore.Components\Components\DesignSystemProvider) is more than 260 characters and therefore it will break.

You can learn how to get rid of that limitation by following [this documentation page](https://learn.microsoft.com/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later), although I'm not 100% sure this will work, I think Visual Studio might have a limitation too. The other option is: move the solution closer to the root of your disk and maybe rename some folders.

I will add this to the README so people will know about this.

Thanks for raising this!

**Comment by ShamilS** [comment]
> Just tried this and its caused by the infamous maximum file path length in Windows.
...
> Thanks for raising this!

Yes. Thank you!

**Comment by jfversluis** [comment]
Added a note to the Part 2 README for this. Thanks again!
